# GPIO is required to read the reed switch / Hall sensor
CONFIG_GPIO=y

# Console output so we can see revolution/speed data over USB-UART
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_SERIAL=y

CONFIG_DISPLAY_ENABLED=y

# Display configs
CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y

# Settings subsystem for persistent storage
CONFIG_SETTINGS=y
CONFIG_SETTINGS_RUNTIME=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
